"""Stage 5 document processing and chunks

Revision ID: 20260716_0003
Revises: 20260716_0002
Create Date: 2026-07-16 16:34:44.121090
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "20260716_0003"
down_revision: str | None = "20260716_0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_revisions",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("metadata_hash", sa.String(length=64), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("change_reason", sa.String(length=80), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "version >= 1", name=op.f("ck_document_revisions_document_revision_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_revisions_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_revisions")),
        sa.UniqueConstraint(
            "document_id", "version", name=op.f("uq_document_revisions_document_id")
        ),
    )
    op.create_index(
        op.f("ix_document_revisions_content_hash"),
        "document_revisions",
        ["content_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_revisions_created_at"), "document_revisions", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_document_revisions_document_id"),
        "document_revisions",
        ["document_id"],
        unique=False,
    )
    op.create_table(
        "document_chunks",
        sa.Column("chunk_key", sa.String(length=64), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("document_version", sa.Integer(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("section_type", sa.String(length=24), nullable=False),
        sa.Column("answer_id", sa.Uuid(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("contextual_text", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("character_count", sa.Integer(), nullable=False),
        sa.Column("has_code", sa.Boolean(), nullable=False),
        sa.Column("language", sa.String(length=40), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "section_type IN ('QUESTION','ACCEPTED_ANSWER','ANSWER','MIXED')",
            name=op.f("ck_document_chunks_document_chunk_section_type_values"),
        ),
        sa.CheckConstraint(
            "character_count >= 0",
            name=op.f("ck_document_chunks_document_chunk_character_count_non_negative"),
        ),
        sa.CheckConstraint(
            "document_version >= 1", name=op.f("ck_document_chunks_document_chunk_version_positive")
        ),
        sa.CheckConstraint(
            "length(text) > 0", name=op.f("ck_document_chunks_document_chunk_text_not_empty")
        ),
        sa.CheckConstraint(
            "ordinal >= 0", name=op.f("ck_document_chunks_document_chunk_ordinal_non_negative")
        ),
        sa.CheckConstraint(
            "token_count >= 0",
            name=op.f("ck_document_chunks_document_chunk_token_count_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["answer_id"],
            ["answers.id"],
            name=op.f("fk_document_chunks_answer_id_answers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_chunks_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_chunks")),
        sa.UniqueConstraint(
            "document_id",
            "document_version",
            "ordinal",
            name=op.f("uq_document_chunks_document_id"),
        ),
    )
    op.create_index(
        op.f("ix_document_chunks_answer_id"), "document_chunks", ["answer_id"], unique=False
    )
    op.create_index(
        op.f("ix_document_chunks_chunk_key"), "document_chunks", ["chunk_key"], unique=True
    )
    op.create_index(
        op.f("ix_document_chunks_content_hash"), "document_chunks", ["content_hash"], unique=False
    )
    op.create_index(
        op.f("ix_document_chunks_document_id"), "document_chunks", ["document_id"], unique=False
    )
    op.create_index(
        "ix_document_chunks_document_version",
        "document_chunks",
        ["document_id", "document_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_chunks_section_type"), "document_chunks", ["section_type"], unique=False
    )
    op.add_column("answers", sa.Column("author_profile_url", sa.String(length=2000), nullable=True))
    op.add_column("answers", sa.Column("sanitized_html", sa.Text(), nullable=True))
    op.add_column("answers", sa.Column("body_hash", sa.String(length=64), nullable=True))
    op.add_column(
        "answers",
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "answers",
        sa.Column(
            "selected_for_corpus",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.add_column("answers", sa.Column("selection_rank", sa.Integer(), nullable=True))
    op.add_column(
        "answers",
        sa.Column(
            "source_missing",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.add_column("answers", sa.Column("content_license", sa.String(length=120), nullable=True))
    op.execute(
        "UPDATE answers SET body_hash = encode(sha256(convert_to(body_text, 'UTF8')), 'hex')"
    )
    op.alter_column("answers", "body_hash", existing_type=sa.String(length=64), nullable=False)
    op.create_check_constraint(
        op.f("ck_answers_answer_selection_rank_positive"),
        "answers",
        "selection_rank IS NULL OR selection_rank >= 1",
    )
    op.create_index(op.f("ix_answers_body_hash"), "answers", ["body_hash"], unique=False)
    op.create_index(op.f("ix_answers_last_seen_at"), "answers", ["last_seen_at"], unique=False)
    op.create_index(
        op.f("ix_answers_selected_for_corpus"), "answers", ["selected_for_corpus"], unique=False
    )
    op.create_index(op.f("ix_answers_source_missing"), "answers", ["source_missing"], unique=False)
    op.add_column(
        "documents", sa.Column("author_profile_url", sa.String(length=2000), nullable=True)
    )
    op.add_column("documents", sa.Column("content_license", sa.String(length=120), nullable=True))
    op.add_column("documents", sa.Column("metadata_hash", sa.String(length=128), nullable=True))
    op.add_column("documents", sa.Column("canonical_text", sa.Text(), nullable=True))
    op.add_column(
        "documents",
        sa.Column(
            "processing_status",
            sa.String(length=16),
            server_default="RAW",
            nullable=False,
        ),
    )
    op.add_column(
        "documents",
        sa.Column(
            "deduplication_status",
            sa.String(length=24),
            server_default="UNIQUE",
            nullable=False,
        ),
    )
    op.add_column("documents", sa.Column("duplicate_of_document_id", sa.Uuid(), nullable=True))
    op.add_column("documents", sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("documents", sa.Column("processing_error", sa.String(length=1000), nullable=True))
    op.add_column(
        "documents",
        sa.Column(
            "selected_answers_count",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    op.execute(
        "UPDATE documents SET last_seen_at = COALESCE(source_updated_at, last_synced_at, updated_at)"
    )
    op.create_check_constraint(
        op.f("ck_documents_document_processing_status_values"),
        "documents",
        "processing_status IN ('RAW','CLEANING','CLEANED','CHUNKING','CHUNKED','FAILED')",
    )
    op.create_check_constraint(
        op.f("ck_documents_document_deduplication_status_values"),
        "documents",
        "deduplication_status IN ('UNIQUE','EXACT_DUPLICATE','POSSIBLE_DUPLICATE')",
    )
    op.create_check_constraint(
        op.f("ck_documents_document_selected_answers_non_negative"),
        "documents",
        "selected_answers_count >= 0",
    )
    op.create_index(
        op.f("ix_documents_deduplication_status"),
        "documents",
        ["deduplication_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_documents_duplicate_of_document_id"),
        "documents",
        ["duplicate_of_document_id"],
        unique=False,
    )
    op.create_index(op.f("ix_documents_last_seen_at"), "documents", ["last_seen_at"], unique=False)
    op.create_index(
        op.f("ix_documents_metadata_hash"), "documents", ["metadata_hash"], unique=False
    )
    op.create_index(
        op.f("ix_documents_processing_status"), "documents", ["processing_status"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_documents_duplicate_of_document_id_documents"),
        "documents",
        "documents",
        ["duplicate_of_document_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("ingestion_failures", sa.Column("document_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_ingestion_failures_document_id"),
        "ingestion_failures",
        ["document_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_ingestion_failures_document_id_documents"),
        "ingestion_failures",
        "documents",
        ["document_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "source_sync_states",
        sa.Column("last_seen_question_creation_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "source_sync_states",
        sa.Column(
            "total_chunks_created",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    op.drop_constraint(
        op.f("ck_source_sync_states_source_sync_state_counters_non_negative"),
        "source_sync_states",
        type_="check",
    )
    op.create_check_constraint(
        op.f("ck_source_sync_states_source_sync_state_counters_non_negative"),
        "source_sync_states",
        "total_questions_fetched >= 0 AND total_answers_fetched >= 0 "
        "AND total_documents_inserted >= 0 AND total_documents_updated >= 0 "
        "AND total_documents_unchanged >= 0 AND total_exact_duplicates >= 0 "
        "AND total_items_skipped >= 0 AND total_errors >= 0 "
        "AND total_chunks_created >= 0",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_source_sync_states_source_sync_state_counters_non_negative"),
        "source_sync_states",
        type_="check",
    )
    op.create_check_constraint(
        op.f("ck_source_sync_states_source_sync_state_counters_non_negative"),
        "source_sync_states",
        "total_questions_fetched >= 0 AND total_answers_fetched >= 0 "
        "AND total_documents_inserted >= 0 AND total_documents_updated >= 0 "
        "AND total_documents_unchanged >= 0 AND total_exact_duplicates >= 0 "
        "AND total_items_skipped >= 0 AND total_errors >= 0",
    )
    op.drop_column("source_sync_states", "total_chunks_created")
    op.drop_column("source_sync_states", "last_seen_question_creation_at")
    op.drop_constraint(
        op.f("fk_ingestion_failures_document_id_documents"),
        "ingestion_failures",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_ingestion_failures_document_id"), table_name="ingestion_failures")
    op.drop_column("ingestion_failures", "document_id")
    op.drop_constraint(
        op.f("fk_documents_duplicate_of_document_id_documents"), "documents", type_="foreignkey"
    )
    op.drop_index(op.f("ix_documents_processing_status"), table_name="documents")
    op.drop_index(op.f("ix_documents_metadata_hash"), table_name="documents")
    op.drop_index(op.f("ix_documents_last_seen_at"), table_name="documents")
    op.drop_index(op.f("ix_documents_duplicate_of_document_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_deduplication_status"), table_name="documents")
    op.drop_constraint(
        op.f("ck_documents_document_selected_answers_non_negative"),
        "documents",
        type_="check",
    )
    op.drop_constraint(
        op.f("ck_documents_document_deduplication_status_values"),
        "documents",
        type_="check",
    )
    op.drop_constraint(
        op.f("ck_documents_document_processing_status_values"),
        "documents",
        type_="check",
    )
    op.drop_column("documents", "selected_answers_count")
    op.drop_column("documents", "processing_error")
    op.drop_column("documents", "last_seen_at")
    op.drop_column("documents", "duplicate_of_document_id")
    op.drop_column("documents", "deduplication_status")
    op.drop_column("documents", "processing_status")
    op.drop_column("documents", "canonical_text")
    op.drop_column("documents", "metadata_hash")
    op.drop_column("documents", "content_license")
    op.drop_column("documents", "author_profile_url")
    op.drop_index(op.f("ix_answers_source_missing"), table_name="answers")
    op.drop_index(op.f("ix_answers_selected_for_corpus"), table_name="answers")
    op.drop_index(op.f("ix_answers_last_seen_at"), table_name="answers")
    op.drop_index(op.f("ix_answers_body_hash"), table_name="answers")
    op.drop_constraint(
        op.f("ck_answers_answer_selection_rank_positive"),
        "answers",
        type_="check",
    )
    op.drop_column("answers", "content_license")
    op.drop_column("answers", "source_missing")
    op.drop_column("answers", "selection_rank")
    op.drop_column("answers", "selected_for_corpus")
    op.drop_column("answers", "last_seen_at")
    op.drop_column("answers", "body_hash")
    op.drop_column("answers", "sanitized_html")
    op.drop_column("answers", "author_profile_url")
    op.drop_index(op.f("ix_document_chunks_section_type"), table_name="document_chunks")
    op.drop_index("ix_document_chunks_document_version", table_name="document_chunks")
    op.drop_index(op.f("ix_document_chunks_document_id"), table_name="document_chunks")
    op.drop_index(op.f("ix_document_chunks_content_hash"), table_name="document_chunks")
    op.drop_index(op.f("ix_document_chunks_chunk_key"), table_name="document_chunks")
    op.drop_index(op.f("ix_document_chunks_answer_id"), table_name="document_chunks")
    op.drop_table("document_chunks")
    op.drop_index(op.f("ix_document_revisions_document_id"), table_name="document_revisions")
    op.drop_index(op.f("ix_document_revisions_created_at"), table_name="document_revisions")
    op.drop_index(op.f("ix_document_revisions_content_hash"), table_name="document_revisions")
    op.drop_table("document_revisions")
    # ### end Alembic commands ###
