"""Initial PostgreSQL schema for PyAnswer Stage 4

Revision ID: 20260715_0001
Revises:
Create Date: 2026-07-16 08:01:54.861106
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '20260715_0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('roles',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("code IN ('USER','EDITOR','ADMIN')", name=op.f('ck_roles_role_code_values')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_table('sources',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('base_url', sa.String(length=2000), nullable=False),
    sa.Column('site', sa.String(length=120), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('target_documents', sa.Integer(), nullable=False),
    sa.Column('max_additional_answers', sa.Integer(), nullable=False),
    sa.Column('page_size', sa.Integer(), nullable=False),
    sa.Column('documents_count', sa.Integer(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_successful_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rate_limit_remaining', sa.Integer(), nullable=False),
    sa.Column('rate_limit_total', sa.Integer(), nullable=False),
    sa.Column('quota_reset_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('current_job_id', sa.Uuid(), nullable=True),
    sa.Column('last_error', sa.String(length=1000), nullable=True),
    sa.Column('api_key_configured', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('IDLE','CHECKING','SYNCING','PAUSED','ERROR','DISABLED')", name=op.f('ck_sources_source_status_values')),
    sa.CheckConstraint("type IN ('STACK_EXCHANGE')", name=op.f('ck_sources_source_type_values')),
    sa.CheckConstraint('max_additional_answers BETWEEN 0 AND 3', name=op.f('ck_sources_source_answers_range')),
    sa.CheckConstraint('page_size BETWEEN 1 AND 100', name=op.f('ck_sources_source_page_size_range')),
    sa.CheckConstraint('target_documents BETWEEN 5000 AND 100000', name=op.f('ck_sources_source_target_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('name', name=op.f('uq_sources_name'))
    )
    op.create_index(op.f('ix_sources_current_job_id'), 'sources', ['current_job_id'], unique=False)
    op.create_index(op.f('ix_sources_status'), 'sources', ['status'], unique=False)
    op.create_table('tags',
    sa.Column('normalized_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    op.create_index(op.f('ix_tags_normalized_name'), 'tags', ['normalized_name'], unique=True)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('users',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('normalized_email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('account_version', sa.Integer(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('blocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blocked_by', sa.Uuid(), nullable=True),
    sa.Column('block_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE','BLOCKED')", name=op.f('ck_users_user_status_values')),
    sa.CheckConstraint('account_version >= 1', name=op.f('ck_users_user_account_version_positive')),
    sa.ForeignKeyConstraint(['blocked_by'], ['users.id'], name=op.f('fk_users_blocked_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_normalized_email'), 'users', ['normalized_email'], unique=True)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_table('audit_events',
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('actor_name', sa.String(length=200), nullable=False),
    sa.Column('actor_role', sa.String(length=16), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=120), nullable=False),
    sa.Column('entity_label', sa.String(length=500), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('request_id', sa.String(length=80), nullable=False),
    sa.Column('batch_id', sa.String(length=80), nullable=True),
    sa.Column('summary', sa.String(length=1000), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("outcome IN ('SUCCESS','FAILURE')", name=op.f('ck_audit_events_audit_outcome_values')),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_events_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_role'), 'audit_events', ['actor_role'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_user_id'), 'audit_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_events_batch_id'), 'audit_events', ['batch_id'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_events_outcome'), 'audit_events', ['outcome'], unique=False)
    op.create_index(op.f('ix_audit_events_request_id'), 'audit_events', ['request_id'], unique=False)
    op.create_table('documents',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('source_url', sa.String(length=2000), nullable=False),
    sa.Column('original_title', sa.String(length=500), nullable=False),
    sa.Column('normalized_title', sa.String(length=500), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_html', sa.Text(), nullable=True),
    sa.Column('author_name', sa.String(length=200), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('answers_count', sa.Integer(), nullable=False),
    sa.Column('accepted_answer_external_id', sa.String(length=120), nullable=True),
    sa.Column('has_code', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('bm25_status', sa.String(length=16), nullable=False),
    sa.Column('vector_status', sa.String(length=16), nullable=False),
    sa.Column('chunks_count', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('editorial_note', sa.String(length=2000), nullable=False),
    sa.Column('hidden_reason', sa.String(length=1000), nullable=True),
    sa.Column('failure_reason', sa.String(length=1000), nullable=True),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_edited_by', sa.Uuid(), nullable=True),
    sa.Column('last_edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("bm25_status IN ('READY','PENDING','FAILED','NOT_INDEXED','OUTDATED')", name=op.f('ck_documents_document_bm25_status_values')),
    sa.CheckConstraint("status IN ('ACTIVE','HIDDEN','PENDING','FAILED','OUTDATED')", name=op.f('ck_documents_document_status_values')),
    sa.CheckConstraint("vector_status IN ('READY','PENDING','FAILED','NOT_INDEXED','OUTDATED')", name=op.f('ck_documents_document_vector_status_values')),
    sa.CheckConstraint('version >= 1', name=op.f('ck_documents_document_version_positive')),
    sa.ForeignKeyConstraint(['last_edited_by'], ['users.id'], name=op.f('fk_documents_last_edited_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_documents_source_id_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('source_id', 'external_id', name=op.f('uq_documents_source_id'))
    )
    op.create_index(op.f('ix_documents_published_at'), 'documents', ['published_at'], unique=False)
    op.create_index(op.f('ix_documents_source_id'), 'documents', ['source_id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_index(op.f('ix_documents_updated_at'), 'documents', ['updated_at'], unique=False)
    op.create_table('feedback',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('response_id', sa.String(length=120), nullable=False),
    sa.Column('value', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=True),
    sa.Column('question', sa.String(length=1000), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("value IN ('positive','negative')", name=op.f('ck_feedback_feedback_value_values')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_feedback_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback')),
    sa.UniqueConstraint('user_id', 'response_id', name=op.f('uq_feedback_user_id'))
    )
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)
    op.create_table('search_history',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('query', sa.String(length=1000), nullable=False),
    sa.Column('view', sa.String(length=16), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sort', sa.String(length=32), nullable=False),
    sa.Column('page_size', sa.Integer(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('took_ms', sa.Integer(), nullable=False),
    sa.Column('answer_preview', sa.String(length=1000), nullable=True),
    sa.Column('insufficient_context', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("mode IN ('bm25','vector','hybrid')", name=op.f('ck_search_history_history_mode_values')),
    sa.CheckConstraint("view IN ('documents','answer')", name=op.f('ck_search_history_history_view_values')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_search_history_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_history'))
    )
    op.create_index(op.f('ix_search_history_created_at'), 'search_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_search_history_user_id'), 'search_history', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token_hash', sa.String(length=64), nullable=False),
    sa.Column('account_version', sa.Integer(), nullable=False),
    sa.Column('remember_me', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_revoked_at'), 'sessions', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('singleton_id', sa.Integer(), nullable=False),
    sa.Column('search_candidates_limit', sa.Integer(), nullable=False),
    sa.Column('reranker_limit', sa.Integer(), nullable=False),
    sa.Column('rag_sources_limit', sa.Integer(), nullable=False),
    sa.Column('default_minimum_confidence', sa.Float(), nullable=False),
    sa.Column('allow_guest_search', sa.Boolean(), nullable=False),
    sa.Column('allow_guest_rag', sa.Boolean(), nullable=False),
    sa.Column('history_retention_days', sa.Integer(), nullable=False),
    sa.Column('audit_retention_days', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('audit_retention_days BETWEEN 30 AND 3650', name=op.f('ck_system_settings_settings_audit_retention_range')),
    sa.CheckConstraint('default_minimum_confidence BETWEEN 0 AND 1', name=op.f('ck_system_settings_settings_confidence_range')),
    sa.CheckConstraint('history_retention_days BETWEEN 1 AND 3650', name=op.f('ck_system_settings_settings_history_retention_range')),
    sa.CheckConstraint('rag_sources_limit BETWEEN 1 AND 20', name=op.f('ck_system_settings_settings_rag_sources_range')),
    sa.CheckConstraint('reranker_limit BETWEEN 1 AND 100', name=op.f('ck_system_settings_settings_reranker_range')),
    sa.CheckConstraint('search_candidates_limit BETWEEN 10 AND 1000', name=op.f('ck_system_settings_settings_candidates_range')),
    sa.CheckConstraint('singleton_id = 1', name=op.f('ck_system_settings_system_settings_singleton')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_system_settings_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('singleton_id', name=op.f('pk_system_settings'))
    )
    op.create_table('user_preferences',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('default_search_mode', sa.String(length=16), nullable=False),
    sa.Column('default_search_view', sa.String(length=16), nullable=False),
    sa.Column('default_page_size', sa.Integer(), nullable=False),
    sa.Column('auto_expand_scores', sa.Boolean(), nullable=False),
    sa.Column('confirm_external_links', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("default_search_mode IN ('bm25','vector','hybrid')", name=op.f('ck_user_preferences_preference_search_mode_values')),
    sa.CheckConstraint("default_search_view IN ('documents','answer')", name=op.f('ck_user_preferences_preference_search_view_values')),
    sa.CheckConstraint('default_page_size IN (10,20,50)', name=op.f('ck_user_preferences_preference_page_size_values')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_preferences'))
    )
    op.create_table('answers',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('author_name', sa.String(length=200), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_answers_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answers')),
    sa.UniqueConstraint('document_id', 'external_id', name=op.f('uq_answers_document_id'))
    )
    op.create_index(op.f('ix_answers_document_id'), 'answers', ['document_id'], unique=False)
    op.create_table('document_tags',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('is_managed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_tags_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_document_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'tag_id', 'is_managed', name=op.f('pk_document_tags'))
    )
    op.create_table('jobs',
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('processed_items', sa.Integer(), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('retry_of_job_id', sa.Uuid(), nullable=True),
    sa.Column('cancellable', sa.Boolean(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('planned_duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("stage IN ('PREPARING','CRAWLING','CLEANING','DEDUPLICATING','CHUNKING','EMBEDDING','INDEXING_BM25','INDEXING_VECTOR','FINALIZING')", name=op.f('ck_jobs_job_stage_values')),
    sa.CheckConstraint("status IN ('QUEUED','RUNNING','COMPLETED','FAILED','CANCELLED')", name=op.f('ck_jobs_job_status_values')),
    sa.CheckConstraint("type IN ('SOURCE_SYNC','DOCUMENT_REINDEX','FULL_REINDEX','HEALTH_CHECK')", name=op.f('ck_jobs_job_type_values')),
    sa.CheckConstraint('progress BETWEEN 0 AND 100', name=op.f('ck_jobs_job_progress_range')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_jobs_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_jobs_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['retry_of_job_id'], ['jobs.id'], name=op.f('fk_jobs_retry_of_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_jobs_source_id_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_created_by'), 'jobs', ['created_by'], unique=False)
    op.create_index(op.f('ix_jobs_document_id'), 'jobs', ['document_id'], unique=False)
    op.create_index(op.f('ix_jobs_source_id'), 'jobs', ['source_id'], unique=False)
    op.create_index(op.f('ix_jobs_stage'), 'jobs', ['stage'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_type'), 'jobs', ['type'], unique=False)
    op.create_index('uq_jobs_active_document_reindex', 'jobs', ['document_id'], unique=True, postgresql_where=sa.text("type = 'DOCUMENT_REINDEX' AND status IN ('QUEUED', 'RUNNING')"))
    op.create_index('uq_jobs_active_full_reindex', 'jobs', ['type'], unique=True, postgresql_where=sa.text("type = 'FULL_REINDEX' AND status IN ('QUEUED', 'RUNNING')"))
    op.create_index('uq_jobs_active_source_sync', 'jobs', ['source_id'], unique=True, postgresql_where=sa.text("type = 'SOURCE_SYNC' AND status IN ('QUEUED', 'RUNNING')"))
    op.create_foreign_key(
        'fk_sources_current_job_id_jobs',
        'sources',
        'jobs',
        ['current_job_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.create_table('saved_documents',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_saved_documents_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_saved_documents_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'document_id', name=op.f('pk_saved_documents'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_documents')
    op.drop_constraint('fk_sources_current_job_id_jobs', 'sources', type_='foreignkey')
    op.drop_index('uq_jobs_active_source_sync', table_name='jobs', postgresql_where=sa.text("type = 'SOURCE_SYNC' AND status IN ('QUEUED', 'RUNNING')"))
    op.drop_index('uq_jobs_active_full_reindex', table_name='jobs', postgresql_where=sa.text("type = 'FULL_REINDEX' AND status IN ('QUEUED', 'RUNNING')"))
    op.drop_index('uq_jobs_active_document_reindex', table_name='jobs', postgresql_where=sa.text("type = 'DOCUMENT_REINDEX' AND status IN ('QUEUED', 'RUNNING')"))
    op.drop_index(op.f('ix_jobs_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_stage'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_source_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_document_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_by'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('document_tags')
    op.drop_index(op.f('ix_answers_document_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_table('user_preferences')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_revoked_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_search_history_user_id'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_created_at'), table_name='search_history')
    op.drop_table('search_history')
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_documents_updated_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_source_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_published_at'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_audit_events_request_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_outcome'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_batch_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_user_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_role'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_normalized_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_tags_normalized_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_sources_status'), table_name='sources')
    op.drop_index(op.f('ix_sources_current_job_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
