from enum import StrEnum


class UserRole(StrEnum):
    USER = "USER"
    EDITOR = "EDITOR"
    ADMIN = "ADMIN"


class AccountStatus(StrEnum):
    ACTIVE = "ACTIVE"
    BLOCKED = "BLOCKED"


class Permission(StrEnum):
    SEARCH_USE = "SEARCH_USE"
    RAG_USE = "RAG_USE"
    PROFILE_MANAGE = "PROFILE_MANAGE"
    HISTORY_MANAGE = "HISTORY_MANAGE"
    SAVED_MANAGE = "SAVED_MANAGE"
    EDITOR_ACCESS = "EDITOR_ACCESS"
    MANAGED_DOCUMENTS_VIEW = "MANAGED_DOCUMENTS_VIEW"
    DOCUMENT_METADATA_EDIT = "DOCUMENT_METADATA_EDIT"
    DOCUMENT_STATUS_CHANGE = "DOCUMENT_STATUS_CHANGE"
    DOCUMENT_REINDEX = "DOCUMENT_REINDEX"
    EDITOR_JOBS_VIEW = "EDITOR_JOBS_VIEW"
    ADMIN_ACCESS = "ADMIN_ACCESS"
    USERS_MANAGE = "USERS_MANAGE"
    SOURCES_MANAGE = "SOURCES_MANAGE"
    ADMIN_JOBS_MANAGE = "ADMIN_JOBS_MANAGE"
    AUDIT_VIEW = "AUDIT_VIEW"
    SYSTEM_VIEW = "SYSTEM_VIEW"
    SYSTEM_SETTINGS_MANAGE = "SYSTEM_SETTINGS_MANAGE"
    SEARCH_INDEX_VIEW = "SEARCH_INDEX_VIEW"
    SEARCH_INDEX_MANAGE = "SEARCH_INDEX_MANAGE"


class SearchMode(StrEnum):
    BM25 = "bm25"
    VECTOR = "vector"
    HYBRID = "hybrid"


class SearchView(StrEnum):
    DOCUMENTS = "documents"
    ANSWER = "answer"


class DocumentStatus(StrEnum):
    ACTIVE = "ACTIVE"
    HIDDEN = "HIDDEN"
    PENDING = "PENDING"
    FAILED = "FAILED"
    OUTDATED = "OUTDATED"


class IndexStatus(StrEnum):
    READY = "READY"
    PENDING = "PENDING"
    FAILED = "FAILED"
    NOT_INDEXED = "NOT_INDEXED"
    OUTDATED = "OUTDATED"


class SearchIndexVersionStatus(StrEnum):
    BUILDING = "BUILDING"
    READY = "READY"
    ACTIVE = "ACTIVE"
    FAILED = "FAILED"
    RETIRED = "RETIRED"


class SearchIndexEntryStatus(StrEnum):
    PENDING = "PENDING"
    INDEXED = "INDEXED"
    FAILED = "FAILED"
    REMOVED = "REMOVED"


class RagResponseStatus(StrEnum):
    GENERATING = "GENERATING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ConfidenceLabel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class ProcessingStatus(StrEnum):
    RAW = "RAW"
    CLEANING = "CLEANING"
    CLEANED = "CLEANED"
    CHUNKING = "CHUNKING"
    CHUNKED = "CHUNKED"
    FAILED = "FAILED"


class DeduplicationStatus(StrEnum):
    UNIQUE = "UNIQUE"
    EXACT_DUPLICATE = "EXACT_DUPLICATE"
    POSSIBLE_DUPLICATE = "POSSIBLE_DUPLICATE"


class ChunkSectionType(StrEnum):
    QUESTION = "QUESTION"
    ACCEPTED_ANSWER = "ACCEPTED_ANSWER"
    ANSWER = "ANSWER"
    MIXED = "MIXED"


class IngestionResultStatus(StrEnum):
    INSERTED = "INSERTED"
    UPDATED = "UPDATED"
    UNCHANGED = "UNCHANGED"
    DUPLICATE = "DUPLICATE"
    SKIPPED = "SKIPPED"
    FAILED = "FAILED"


class SourceType(StrEnum):
    STACK_EXCHANGE = "STACK_EXCHANGE"


class SourceStatus(StrEnum):
    IDLE = "IDLE"
    CHECKING = "CHECKING"
    SYNCING = "SYNCING"
    PAUSED = "PAUSED"
    ERROR = "ERROR"
    DISABLED = "DISABLED"


class JobType(StrEnum):
    SOURCE_SYNC = "SOURCE_SYNC"
    DOCUMENT_REPROCESS = "DOCUMENT_REPROCESS"
    DOCUMENT_REINDEX = "DOCUMENT_REINDEX"
    FULL_REINDEX = "FULL_REINDEX"
    HEALTH_CHECK = "HEALTH_CHECK"
    SEARCH_INDEX_VALIDATE = "SEARCH_INDEX_VALIDATE"
    SEARCH_INDEX_CLEANUP = "SEARCH_INDEX_CLEANUP"


class JobStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class JobStage(StrEnum):
    PREPARING = "PREPARING"
    FETCHING_QUESTIONS = "FETCHING_QUESTIONS"
    FETCHING_ANSWERS = "FETCHING_ANSWERS"
    WAITING_BACKOFF = "WAITING_BACKOFF"
    PROCESSING = "PROCESSING"
    CRAWLING = "CRAWLING"
    CLEANING = "CLEANING"
    DEDUPLICATING = "DEDUPLICATING"
    CHUNKING = "CHUNKING"
    EMBEDDING = "EMBEDDING"
    INDEXING_BM25 = "INDEXING_BM25"
    INDEXING_VECTOR = "INDEXING_VECTOR"
    FINALIZING = "FINALIZING"


class SourceSyncMode(StrEnum):
    AUTO = "AUTO"
    INITIAL = "INITIAL"
    INCREMENTAL = "INCREMENTAL"


class JobEventLevel(StrEnum):
    DEBUG = "DEBUG"
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"


class WorkerInstanceStatus(StrEnum):
    STARTING = "STARTING"
    RUNNING = "RUNNING"
    STOPPING = "STOPPING"
    STOPPED = "STOPPED"


class FeedbackValue(StrEnum):
    POSITIVE = "positive"
    NEGATIVE = "negative"


class AuditOutcome(StrEnum):
    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"


class AuditAction(StrEnum):
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"
    REGISTER = "REGISTER"
    UPDATE_PROFILE = "UPDATE_PROFILE"
    UPDATE_DOCUMENT_METADATA = "UPDATE_DOCUMENT_METADATA"
    HIDE_DOCUMENT = "HIDE_DOCUMENT"
    RESTORE_DOCUMENT = "RESTORE_DOCUMENT"
    REINDEX_DOCUMENT = "REINDEX_DOCUMENT"
    BULK_HIDE_DOCUMENTS = "BULK_HIDE_DOCUMENTS"
    BULK_RESTORE_DOCUMENTS = "BULK_RESTORE_DOCUMENTS"
    BULK_REINDEX_DOCUMENTS = "BULK_REINDEX_DOCUMENTS"
    CHANGE_USER_ROLE = "CHANGE_USER_ROLE"
    BLOCK_USER = "BLOCK_USER"
    UNBLOCK_USER = "UNBLOCK_USER"
    UPDATE_SOURCE = "UPDATE_SOURCE"
    TEST_SOURCE = "TEST_SOURCE"
    START_SOURCE_SYNC = "START_SOURCE_SYNC"
    STOP_SOURCE_SYNC = "STOP_SOURCE_SYNC"
    RETRY_JOB = "RETRY_JOB"
    CANCEL_JOB = "CANCEL_JOB"
    START_FULL_REINDEX = "START_FULL_REINDEX"
    HEALTH_CHECK = "HEALTH_CHECK"
    UPDATE_SYSTEM_SETTINGS = "UPDATE_SYSTEM_SETTINGS"
    ACTIVATE_SEARCH_INDEX = "ACTIVATE_SEARCH_INDEX"
    VALIDATE_SEARCH_INDEX = "VALIDATE_SEARCH_INDEX"
    CLEANUP_SEARCH_INDEX = "CLEANUP_SEARCH_INDEX"


class AuditEntityType(StrEnum):
    AUTH = "AUTH"
    USER = "USER"
    DOCUMENT = "DOCUMENT"
    DOCUMENT_BATCH = "DOCUMENT_BATCH"
    SOURCE = "SOURCE"
    JOB = "JOB"
    SYSTEM = "SYSTEM"
    SEARCH_INDEX = "SEARCH_INDEX"
